image:
  repository: 339935010405.dkr.ecr.eu-west-1.amazonaws.com/sdc-lake-dev/data-service
  tag: latest

dynamodb:
  tableName: sdc-lake-dev-resources

aws:
  region: eu-west-1
  accountId: 339935010405

entra:
  tenantId: 83e36855-c258-41a8-9c37-d5406de024a3
  clientId: 3100f22d-72cb-41da-9f6c-7c0c4c3e5ec9
