apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioning-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioning-service
  template:
    metadata:
      labels:
        app: provisioning-service
    spec:
      serviceAccountName: provisioning-service  # linked to Pod Identity
      containers:
        - name: provisioning-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: SQS_QUEUE_URL
              value: {{ .Values.sqs.queueUrl }}
            - name: DYNAMODB_TABLE
              value: {{ .Values.dynamodb.tableName }}
            - name: COGNITO_IDENTITY_POOL_ID
              value: {{ .Values.cognito.identityPoolId }}
            - name: COGNITO_USER_POOL_ID
              value: {{ .Values.cognito.userPoolId }}
            - name: COGNITO_USER_POOL_CLIENT_ID
              value: {{ .Values.cognito.userPoolClientId }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_ACCOUNT_ID
              value: {{ .Values.aws.accountId | quote }}
            - name: RESOURCE_PREFIX
              value: {{ .Values.resourcePrefix }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
