image:
  repository: 339935010405.dkr.ecr.eu-west-1.amazonaws.com/sdc-lake-dev/provisioning-service
  tag: latest

sqs:
  queueUrl: https://sqs.eu-west-1.amazonaws.com/339935010405/sdc-lake-dev-provisioning

dynamodb:
  tableName: sdc-lake-dev-resources

aws:
  region: eu-west-1
  accountId: 339935010405

resourcePrefix: sdc-lake-dev
